# Generated by Django 4.0.4 on 2022-06-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comm_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
